# Generated by Django 5.1.3 on 2024-11-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
