# Generated by Django 5.1.3 on 2024-11-26 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_students_startdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('py', 'Python'), ('js', 'JavaScript'), ('c', 'C++'), ('an', 'Android')], max_length=20)),
                ('course_num', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Номер курса')),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AddField(
            model_name='students',
            name='age',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='students',
            name='active',
            field=models.BooleanField(verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='students',
            name='sex',
            field=models.CharField(choices=[('m', 'Мужчина'), ('w', 'Женщина')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='students',
            name='startDate',
            field=models.DateField(null=True, verbose_name='Дата начала обучения'),
        ),
        migrations.AlterField(
            model_name='students',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterUniqueTogether(
            name='students',
            unique_together={('name', 'surname')},
        ),
        migrations.AlterModelTable(
            name='students',
            table='students',
        ),
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.ManyToManyField(to='main.course'),
        ),
        migrations.AddIndex(
            model_name='students',
            index=models.Index(fields=['surname'], name='students_surname_bf4929_idx'),
        ),
    ]
