# Generated by Django 5.1.3 on 2024-11-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_alter_students_options_students_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AddField(
            model_name='students',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фoто'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'course_num')},
        ),
    ]
