# Generated by Django 5.1.3 on 2024-11-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_course_options_students_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['surname'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Окончание курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Начало курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
