# Generated by Django 5.1.3 on 2024-11-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_students_options_course_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name', 'course_num'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.ManyToManyField(blank=True, to='main.course', verbose_name='Посещаемые курсы'),
        ),
    ]
