# Generated by Django 5.1.3 on 2024-11-27 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_course_options_alter_students_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='startDate',
        ),
    ]
