# Generated by Django 5.1.3 on 2024-11-27 21:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_students_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='sex',
            field=models.CharField(choices=[('m', 'Мужчина'), ('w', 'Женщина')], max_length=1, verbose_name='Пол'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students')),
            ],
            options={
                'verbose_name': 'Оценки',
            },
        ),
    ]
